### ISSUE TITLE
Performance suggestions and benchmarking 

### ISSUE THREAD

**Issue by sui-ting-chloe-hui** [loosolab/denis#3]
Hi, 

I am currently running an ATAC-seq dataset with 16 samples (with plans to expand in the future). The dataset involves two conditions, four treatments, and two replicates per treatment, and I would like to use DENIS for my donwstream analysis for TF and motifs searching.  I have some questions regarding the pipeline's performance and benchmarking : 
1. Do you have any performance recommendations for this pipeline? 
2. Specifically, how many CPUs does the pipeline requires?

Best,
Chloe

**Comment by hschult** [comment]
Hi Chloe,

thanks for your interest in the DENIS pipeline!

There is no minimum number of cores. I have successfully run this pipeline with 1 core. However, the number of cores greatly affects the runtime. Especially with a bigger dataset, you want to have as many cores as possible. I usually use something between 6-12 cores, which is reasonably fast. Still, expect a few hours of runtime. The runtime also depends on the size of your data and the number of motifs found. So you might have a rough idea of how long it will take.

Best wishes
Hendrik
